export const categoryIcons: Record<string, string> = {
  "theme-park": "🎢",
  zoo: "🦁",
  aquarium: "🐠",
  park: "🌳",
  "indoor-play": "🏠",
  "science-museum": "🔬",
  museum: "🏛️",
  craft: "🎨",
  "fruit-picking": "🍓",
  "hot-spring-pool": "♨️",
  athletic: "🧗",
  "art-museum": "🖼️",
  ski: "⛷️",
  hotel: "🏨",
  experience: "✨",
  "nature-park": "🌲",
  viewpoint: "🔭",
  scenic: "🏞️",
  "indoor-theme-park": "🎡",
  "game-center": "🎮",
};

export function categoryIcon(categoryId: string): string {
  return categoryIcons[categoryId] ?? "📍";
}

export const categoryIconImages: Record<string, string> = {
  "theme-park": "/images/categories/theme-park.webp",
  zoo: "/images/categories/zoo.webp",
  aquarium: "/images/categories/aquarium.webp",
  park: "/images/categories/park.webp",
  "indoor-play": "/images/categories/indoor-play.webp",
  "science-museum": "/images/categories/science-museum.webp",
  museum: "/images/categories/museum.webp",
  craft: "/images/categories/craft.webp",
  "fruit-picking": "/images/categories/fruit-picking.webp",
  "hot-spring-pool": "/images/categories/hot-spring-pool.webp",
  athletic: "/images/categories/athletic.webp",
  "art-museum": "/images/categories/art-museum.webp",
  ski: "/images/categories/ski.webp",
  hotel: "/images/categories/hotel.webp",
  experience: "/images/categories/experience.webp",
  "nature-park": "/images/categories/nature-park.webp",
  viewpoint: "/images/categories/viewpoint.webp",
  scenic: "/images/categories/scenic.webp",
  "indoor-theme-park": "/images/categories/indoor-theme-park.webp",
  "game-center": "/images/categories/game-center.webp",
};

export const prefectureGradients: Record<string, string> = {
  shizuoka: "from-sky-400 via-cyan-400 to-emerald-400",
  nagano: "from-emerald-500 via-teal-500 to-sky-500",
  yamanashi: "from-fuchsia-400 via-violet-500 to-indigo-500",
  tokyo: "from-rose-400 via-pink-400 to-orange-400",
  tochigi: "from-yellow-400 via-amber-400 to-orange-500",
  saitama: "from-lime-400 via-green-400 to-teal-400",
  niigata: "from-blue-400 via-indigo-400 to-purple-500",
  chiba: "from-cyan-400 via-blue-400 to-sky-500",
  kanagawa: "from-violet-400 via-purple-400 to-pink-500",
  ibaraki: "from-sky-400 via-blue-400 to-emerald-400",
  gunma: "from-amber-400 via-orange-400 to-rose-400",
  osaka: "from-rose-400 via-amber-400 to-sky-500",
  hyogo: "from-cyan-500 via-lime-400 to-amber-400",
  kyoto: "from-red-500 via-stone-400 to-emerald-500",
  aichi: "from-green-500 via-yellow-400 to-red-500",
  fukuoka: "from-purple-500 via-cyan-400 to-lime-400",
  hiroshima: "from-red-600 via-amber-300 to-teal-500",
  miyagi: "from-cyan-500 via-sky-400 to-emerald-500",
  kagawa: "from-lime-500 via-emerald-400 to-sky-400",
  kumamoto: "from-rose-600 via-amber-400 to-emerald-500",
  okayama: "from-pink-500 via-rose-400 to-amber-300",
  ishikawa: "from-sky-600 via-cyan-400 to-indigo-500",
  oita: "from-orange-500 via-amber-400 to-emerald-500",
  fukushima: "from-emerald-600 via-lime-400 to-rose-400",
  ehime: "from-orange-500 via-amber-300 to-sky-500",
  nagasaki: "from-blue-600 via-cyan-400 to-amber-300",
  toyama: "from-cyan-500 via-sky-400 to-emerald-500",
  fukui: "from-emerald-600 via-teal-400 to-amber-400",
  gifu: "from-emerald-600 via-lime-400 to-sky-500",
  mie: "from-indigo-600 via-violet-400 to-amber-400",
  nara: "from-orange-500 via-rose-400 to-pink-500",
  hokkaido: "from-sky-600 via-cyan-400 to-indigo-500",
  yamagata: "from-rose-600 via-pink-400 to-emerald-500",
  okinawa: "from-cyan-500 via-sky-400 to-fuchsia-500",
  shiga: "from-sky-600 via-cyan-400 to-emerald-400",
};

export const prefectureIconImages: Record<string, string> = {
  shizuoka: "/images/prefectures/shizuoka.webp",
  nagano: "/images/prefectures/nagano.webp",
  yamanashi: "/images/prefectures/yamanashi.webp",
  tokyo: "/images/prefectures/tokyo.webp",
  tochigi: "/images/prefectures/tochigi.webp",
  saitama: "/images/prefectures/saitama.webp",
  niigata: "/images/prefectures/niigata.webp",
  chiba: "/images/prefectures/chiba.webp",
  kanagawa: "/images/prefectures/kanagawa.webp",
  ibaraki: "/images/prefectures/ibaraki.webp",
  gunma: "/images/prefectures/gunma.webp",
  osaka: "/images/prefectures/osaka.webp",
  hyogo: "/images/prefectures/hyogo.webp",
  kyoto: "/images/prefectures/kyoto.webp",
  aichi: "/images/prefectures/aichi.webp",
  fukuoka: "/images/prefectures/fukuoka.webp",
  hiroshima: "/images/prefectures/hiroshima.webp",
  miyagi: "/images/prefectures/miyagi.webp",
  kagawa: "/images/prefectures/kagawa.webp",
  kumamoto: "/images/prefectures/kumamoto.webp",
  okayama: "/images/prefectures/okayama.webp",
  ishikawa: "/images/prefectures/ishikawa.webp",
  oita: "/images/prefectures/oita.webp",
  fukushima: "/images/prefectures/fukushima.webp",
  ehime: "/images/prefectures/ehime.webp",
  nagasaki: "/images/prefectures/nagasaki.webp",
  toyama: "/images/prefectures/toyama.webp",
  fukui: "/images/prefectures/fukui.webp",
  gifu: "/images/prefectures/gifu.webp",
  mie: "/images/prefectures/mie.webp",
  nara: "/images/prefectures/nara.webp",
  hokkaido: "/images/prefectures/hokkaido.svg",
  yamagata: "/images/prefectures/yamagata.svg",
  okinawa: "/images/prefectures/okinawa.webp",
  shiga: "/images/prefectures/shiga.webp",
};

export const prefectureEmoji: Record<string, string> = {
  shizuoka: "🗻",
  nagano: "🏔️",
  yamanashi: "🍇",
  tokyo: "🗼",
  tochigi: "🍓",
  saitama: "🌻",
  niigata: "🌾",
  chiba: "🥜",
  kanagawa: "🌊",
  ibaraki: "🌊",
  gunma: "♨️",
  osaka: "🏯",
  hyogo: "🌉",
  kyoto: "⛩️",
  aichi: "🏮",
  fukuoka: "🍜",
  hiroshima: "🦪",
  miyagi: "🌙",
  kagawa: "🫒",
  kumamoto: "🏯",
  okayama: "🍑",
  ishikawa: "🪭",
  oita: "♨️",
  fukushima: "🍑",
  ehime: "🍊",
  nagasaki: "⛵",
  toyama: "🏔️",
  fukui: "🦖",
  gifu: "🏞️",
  mie: "🥷",
  nara: "🦌",
  hokkaido: "❄️",
  yamagata: "🍒",
  okinawa: "🌺",
  shiga: "🌊",
};
