export const categoryIcons: Record<string, string> = {
  "theme-park": "🎢",
  zoo: "🦁",
  aquarium: "🐠",
  park: "🌳",
  "indoor-play": "🏠",
  "science-museum": "🔬",
  museum: "🏛️",
  craft: "🎨",
  "fruit-picking": "🍓",
  "hot-spring-pool": "♨️",
  athletic: "🧗",
  "art-museum": "🖼️",
  ski: "⛷️",
  hotel: "🏨",
  experience: "✨",
  "nature-park": "🌲",
  viewpoint: "🔭",
  scenic: "🏞️",
  "indoor-theme-park": "🎡",
  "game-center": "🎮",
};

export function categoryIcon(categoryId: string): string {
  return categoryIcons[categoryId] ?? "📍";
}

export const prefectureGradients: Record<string, string> = {
  shizuoka: "from-sky-400 via-cyan-400 to-emerald-400",
  nagano: "from-emerald-500 via-teal-500 to-sky-500",
  yamanashi: "from-fuchsia-400 via-violet-500 to-indigo-500",
  tokyo: "from-rose-400 via-pink-400 to-orange-400",
  tochigi: "from-yellow-400 via-amber-400 to-orange-500",
  saitama: "from-lime-400 via-green-400 to-teal-400",
  niigata: "from-blue-400 via-indigo-400 to-purple-500",
  chiba: "from-cyan-400 via-blue-400 to-sky-500",
  kanagawa: "from-violet-400 via-purple-400 to-pink-500",
  ibaraki: "from-sky-400 via-blue-400 to-emerald-400",
  gunma: "from-amber-400 via-orange-400 to-rose-400",
  osaka: "from-rose-400 via-amber-400 to-sky-500",
  hyogo: "from-cyan-500 via-lime-400 to-amber-400",
  kyoto: "from-red-500 via-stone-400 to-emerald-500",
  aichi: "from-green-500 via-yellow-400 to-red-500",
  fukuoka: "from-purple-500 via-cyan-400 to-lime-400",
  hiroshima: "from-red-600 via-amber-300 to-teal-500",
};

export const prefectureIconImages: Record<string, string> = {
  shizuoka: "/images/prefectures/shizuoka.webp",
  nagano: "/images/prefectures/nagano.webp",
  yamanashi: "/images/prefectures/yamanashi.webp",
  tokyo: "/images/prefectures/tokyo.webp",
  tochigi: "/images/prefectures/tochigi.webp",
  saitama: "/images/prefectures/saitama.webp",
  niigata: "/images/prefectures/niigata.webp",
  chiba: "/images/prefectures/chiba.webp",
  kanagawa: "/images/prefectures/kanagawa.webp",
  ibaraki: "/images/prefectures/ibaraki.webp",
  gunma: "/images/prefectures/gunma.webp",
  osaka: "/images/prefectures/osaka.webp",
  hyogo: "/images/prefectures/hyogo.webp",
  kyoto: "/images/prefectures/kyoto.webp",
  aichi: "/images/prefectures/aichi.webp",
  fukuoka: "/images/prefectures/fukuoka.webp",
  hiroshima: "/images/prefectures/hiroshima.webp",
};

export const prefectureEmoji: Record<string, string> = {
  shizuoka: "🗻",
  nagano: "🏔️",
  yamanashi: "🍇",
  tokyo: "🗼",
  tochigi: "🍓",
  saitama: "🌻",
  niigata: "🌾",
  chiba: "🥜",
  kanagawa: "🌊",
  ibaraki: "🌊",
  gunma: "♨️",
  osaka: "🏯",
  hyogo: "🌉",
  kyoto: "⛩️",
  aichi: "🏮",
  fukuoka: "🍜",
  hiroshima: "🦪",
};
